package com.netcracker.shaw.element.pageor;
import static com.netcracker.shaw.factory.Locator.*;


import org.openqa.selenium.By;

import com.netcracker.shaw.at_shaw_sd.util.Constants;
import com.netcracker.shaw.at_shaw_sd.util.Utility;
import com.netcracker.shaw.element.PageElement;
import com.netcracker.shaw.factory.ByType;
import com.netcracker.shaw.factory.Locator;

/**
 * @author Ramesh Reddy K (raka0617)
 *
 * Aug 10, 2018
 */

public enum OrderCreationPageElement implements PageElement {
	
	/**************** STUB INFORMATION *******************/
	
	 HPSA(XPATH,getPropValue("hpsa")),
	 HPSA_PHONE_LINE(XPATH,getPropValue("hpsaPhoneLine")),
	 HPSA_WIFI(XPATH,getPropValue("hpsaWifi")),
	 HPSA_CABLE_TV(XPATH,getPropValue("hpsaCableTv")),
	 HPSA_INTERNET(XPATH,getPropValue("hpsaInternet")),
	 CONVERGED_HARDWARE_STUB(XPATH,getPropValue("convergedHardwareStub")),
	 SET_CABLE_TV(XPATH,getPropValue("SetCableTV")),
	 FIELD_FORCE_MANAGEMENT(XPATH,getPropValue("fieldForceManagement")),
     FFM_SERVICE_CALL(XPATH,getPropValue("ffmServiceCall")), 
     ESI(XPATH,getPropValue("esi")),
     GET_ESI_EMAIL(XPATH,getPropValue("getESIEmai")),
     CHANGE_MODE_FOR_EMAIL(XPATH,getPropValue("changeModeForEmail")),
     EMAIL_TOGGLE_BTN(XPATH,getPropValue("emailToggleBtn")),
     STUB_CLEC_TAB(XPATH,getPropValue("stubCLECTab")),
     CLECTAB_LSR_BTN(XPATH,getPropValue("clecLSRBtn")),
     STUB_AWS_PUT_MODE(XPATH,getPropValue("stubAWSPUTmode")),
     
	    
	/*################### CUSTOMER INFORMATION ########################*/
    HOMEPAGE_TAB(XPATH,getPropValue("homepageTab")), 
    NAVIGATION_TAB(XPATH,getPropValue("NavigationTab")),
    DOCUMENTS(XPATH,getPropValue("documents")),
    OFFER_FILTERING_DASBOARD_CHECHBOX(XPATH,getPropValue("offerFilteringDasboardCheckBox")),
    NEW_REGIONAL_SEGMENT(XPATH,getPropValue("newRegionalSegment")),
    NEW_CUSTOMER_SEGMENT(XPATH,getPropValue("newCustomerSegment")),
    
    NEW_PARTNER_SEGMENT(XPATH,getPropValue("newPartnerSegment")),
    NEW_HYBRID_SEG(XPATH,getPropValue("newHybridSeg")),
    
    REGIONAL_SEGMENT_NAME_INPUT(XPATH,getPropValue("regionalSegmentNameInput")),
    REGIONAL_SEGMENT_ID_INPUT(XPATH,getPropValue("regionalSegmentIdInput")),
    ACTIVE_START_DATE_ICON(XPATH,getPropValue("ActiveStartDateIcon")),
    ACTIVE_START_DATE_OK_BTN(XPATH,getPropValue("ActiveStartDateOkBtn")),
    TIME_INPUT(XPATH,getPropValue("TimeInput")),
    RESTRICTED_TO_NEW_CUSTOMER(XPATH,getPropValue("restrictedToNewCustomer")),
    RESTRICTED_TO_EXIST_CUSTOMER(XPATH,getPropValue("restrictedToExistCustomer")),
    PARTNER_FIDO(XPATH,getPropValue("partnerFido")),
    PARTNER_ROGER(XPATH,getPropValue("partnerRoger")),
    PARTNER_SHAW_MOBILE(XPATH,getPropValue("partnerShawMobile")),
    PARTNER_FREEDOM(XPATH,getPropValue("partnerFreedom")),
    RESTRICTED_ADD_BTN(XPATH,getPropValue("restrictedAddBtn")),
    PARTNER_NAME_ADD_BTN(XPATH,getPropValue("partnerNameAddBtn")),
    REGION_DROP_DOWN(XPATH,getPropValue("regionDropDown")),
    REGION_TEXT_AREA(XPATH,getPropValue("RegionTextArea")),
    AB(XPATH,getPropValue("AB")),
    SK(XPATH,getPropValue("SK")),
    POSTAL_CODE_INPUT(XPATH,getPropValue("postalCodeInput")),
    POSTAL_CODE_ADD_BTN(XPATH,getPropValue("postalCodeAddBtn")),
    CREATE_BTN1(XPATH,getPropValue("creataBtn")),
    REGIONAL_SEGMENT2_CHECK_BOX(XPATH,getPropValue("regionalSegment2CheckBox")),
    REGIONAL_SEGMENT2(XPATH,getPropValue("regionalSegment2")),
    DELETE_BTN(XPATH,getPropValue("DeleteBtn")),
    REGIONAL_SEGMENT3(XPATH,getPropValue("regionalSegment3")),
    CUSTOMER_SEGMENT(XPATH,getPropValue("customerSegment")),
	
    
    NEW_DISCONNECT_MAPPING(XPATH,getPropValue("newDiscountMapping")),
    DISCOUNT_INPUT(XPATH,getPropValue("DiscountInput")),
    TWO_YVP_INTERNET_TV_AGREEMENT_DISCOUNT(XPATH,getPropValue("2YVPinternetTVagreementDiscount")),
    FREEDOM_INTERNET_150_DISCOUNT(XPATH,getPropValue("freedomInternet150Discount")),
    FUNCTIONAL_GROUP_INPUT(XPATH,getPropValue("functionalGroupInput")),
    FUNCTIONAL_GROUPS_INPUT(XPATH,getPropValue("functionalGroupsInput")),
    SEGMENTS_INPUT(XPATH,getPropValue("SegmentsInput")),
    HYBRID_SEG_INPUT(XPATH,getPropValue("HybridSegInput")),
    SEGMENTS_DEP_INPUT(XPATH,getPropValue("Segments(Dep)Input")),
    HYBRID(XPATH,getPropValue("Hybrid")),
    PUBLIC_CHANGES(XPATH,getPropValue("publicChanges")),
    SEGMENT_PUBLIC_CHANGES(XPATH,getPropValue("segmentPublicChanges")),
    HYBRID_PUBLIC_CHANGES(XPATH,getPropValue("hybridPublicChanges")),
    RETAIL_FUNCTION(XPATH,getPropValue("RetailFunction")),
    
	CUSTOMER_AND_ID_TAB(LINK_TEXT,getPropValue("customerIdTab")),
	FIRSTNAME(ID,getPropValue("firstName")),
	LASTNAME(ID,getPropValue("lastName")),
	ACCOUNT_TYPE(ID,getPropValue("accountType")),
	ACCOUNT_HOLDER(XPATH,getPropValue("accountHolder")),
	CUST_EMAIL_ADDRESS(XPATH,getPropValue("custEmailAddress")),
	CUST_PHONENUMBER(ID,getPropValue("custPhoneNbr")),
	VALIDATE_PHNBR_BTN(XPATH,getPropValue("validatePhNbrBtn")),
	VALIDATE_EMAIL_BTN(XPATH,getPropValue("validateEmailBtn")),
	AUTHENCTICATION_TYPE(ID,getPropValue("authenticationType")),
	PIN(XPATH,getPropValue("pin")),
	PIN1(ID,getPropValue("pin1")),
	BILLING_PREFERENCE_TAB(XPATH,getPropValue("billingPreferenceTab")),
	SERVICE_LOCATION_RADIO_BTN(XPATH,getPropValue("serviceLocationRadioBtn")),
	BILL_TYPE_PAPER(XPATH,getPropValue("billType_Paper")),
	BILL_TYPE_EMAIL(XPATH,getPropValue("billType_eBill")),
		
	/*################### CUSTOMER INFORMATION MDU ########################*/
	BUSINESS_NAME(XPATH,getPropValue("Business_Name")),
	BUSINESS_FIRST_NAME(XPATH,getPropValue("Business_first_name")),
	BUSINESS_LASTNAME(XPATH,getPropValue("Business_last_name")),
	PERSONAL_ID_PIN(XPATH,getPropValue("personal_id_pin")),
	CUST_MOBILE(XPATH,getPropValue("customer_mobile")),
	CUST_EMAIL(XPATH,getPropValue("customer_email")),
	INSTALL_OPTION_DELAY_CREW(ID,getPropValue("installOption_delay_crew")),
	INSTALL_OPTION_MAILOUT(ID,getPropValue("installOption_mailout")),
	INSTALL_OPTION(XPATH,getPropValue("install_option")),
	
	/*################## PHONE PRODUCT INFORMATION ######################*/
	
	ADD_SERVICES_AND_FEATURES_TAB(LINK_TEXT,getPropValue("addServices")),
	ADD_PHONE_PROD(XPATH,getPropValue("addPhoneProduct")),
	PHONE_PROD_LIST(XPATH,getPropValue("selectPhoneProduct")),
	SELECT_PHONE_PROD2(XPATH,getPropValue("selectPhoneProduct2")),
	SELECT_PHONE_PROD3(XPATH,getPropValue("selectPhoneProduct3")),
	SELECT_NUMBER(XPATH,getPropValue("selectNumber")),
	PHONE_WRENCH_BUTTON(XPATH,getPropValue("phoneWrenchButton")),
	PHONE_WRENCH_BUTTON2(XPATH,getPropValue("phoneWrenchButton2")),
	CHOOSENUMBER(XPATH,getPropValue("chooseNbr")),
	CHANGE_CUST_NBR(XPATH,getPropValue("changeCustNbr")),
	PHONENUMBER_FROM_LIST(XPATH,getPropValue("phoneNbrFromList")),
	ASSIGN_BUTTON(XPATH,getPropValue("assignButton")),
	LISTINGTYPE_LIST(XPATH,getPropValue("listingTypeList")),
	LISTINGTYPE_LIST1(XPATH,getPropValue("listingTypeList1")),
	NO_LISTING(XPATH,getPropValue("listingType")),
	FOUR_ONE_ONE_ONLY(XPATH,getPropValue("411Only")),
	VOICEMAIL_BUTTON(XPATH,getPropValue("voiceMailButton")),
	SECONDARY_VOICEMAIL_BTN(XPATH,getPropValue("secondaryVoiceMailBtn")),
	PHONE_HARDWARE_DROPDOWN(XPATH,getPropValue("phoneHardwareDropDown")),
	PHONEHARDWARE(XPATH,getPropValue("phoneHardware")),
	PH_SERIALNUMBERFIELD(XPATH,getPropValue("phSerialNbrField")),
	HARDWARE_OK_BUTTON(XPATH,getPropValue("hardwareOKButton")),
	VALIDATE_BUTTON(XPATH,getPropValue("validateButton")),
	SELECT_PHONE_SERVICE(XPATH,getPropValue("selectPhoneSvc")),
	PHONE_PORT_OUT(XPATH,getPropValue("phonePortOut")),
	PORT_OUT_OPTION(XPATH,getPropValue("portOutOption")),

	PORT_NUMBER_RADIO_BUTTON(XPATH,getPropValue("PortRadioButton")),
	PORTED_NUMBER(XPATH,getPropValue("PortedNumber")),
	PORT_NOW(XPATH,getPropValue("PortNow")),
	PERSONAL_PHONE_NBR_FIELD(XPATH,getPropValue("personalphNbrField")),
	DISTINCTIVE_RING_NBR_FIELD(XPATH,getPropValue("DistinctiveRingNbrField")),
    LANDLINE_RADIO_BUTTON(XPATH,getPropValue("LandlineRadioButton")),  
    DROP_DOWN_CLASS(XPATH,getPropValue("DropDownClass")),
    SERVICE_PROVIDER_DROP_DOWN(XPATH,getPropValue("ServiceProviderDropDown")),
    SERVICE_PROVIDER_VALUE(XPATH,getPropValue("ServiceProviderValue")), 
    RESELLER_DROP_DOWN(XPATH,getPropValue("ResellerDropDown")),
    RESELLER_VALUE(XPATH,getPropValue("ResellerValue")),
    CUSTOMER_LIFELINE_YES(XPATH,getPropValue("CustomerLifeLineYes")),
    CUSTOMER_LIFELINE_NO(XPATH,getPropValue("CustomerLifeLineNo")),
    SHAW_SERVICE_REQUESTED_NO(XPATH,getPropValue("ShawServiceRequestedNo")),
    PREVIOUS_PROVIDER_ACCOUNT_NUMBER(XPATH,getPropValue("PreviousProviderAccount")),
    LISTINGTYPE411ONLY(XPATH,getPropValue("listingType411Only")),   
    DISTINCTIVE_RING_INCREMENT1(XPATH,getPropValue("distinctiveRingIncrement1")),
    DISTINCTIVE_RING_INCREMENT2(XPATH,getPropValue("distinctiveRingIncrement2")),
    DR_SELECT_NUMBER(XPATH,getPropValue("drSelectNumber")),
    FEATURES_TAB(XPATH,getPropValue("featuresTab")),
    RING_PATTERN_DROP_DOWN(XPATH,getPropValue("ringPatternList")),
    TYPE_3_RING_SHORT(XPATH,getPropValue("3ShortRingType")),
    REMOVE_PERSONAL_PHONE_HARDWARE(XPATH,getPropValue("removePersonalPhoneHardware")),
	CONFIRM_PRODUCT_REMOVE(XPATH,getPropValue("confirmProductRemove")),
	SECONDARY_PHONE_PRODUCT(XPATH,getPropValue("secondaryPhoneProduct")),
	SECONDARY_PHONE_PRODUCT_LIST(XPATH,getPropValue("secondPhoneProductList")),
	SECOND_PHONE_PROD_LIST(XPATH,getPropValue("secondPhoneProdList")),
	THIRD_PHONE_PROD_LIST(XPATH,getPropValue("thirdPhoneProdList")),
	PHONE_NOT_SELECT(XPATH,getPropValue("phoneNotSelected")),
	PERSONAL_PHONE_SELECT(XPATH,getPropValue("personalPhoneSelect")),
	SECONDARY_PERSONAL_PHONE_SELECT(XPATH,getPropValue("secondaryPersonalPhoneSelect")),
	EMPLOYEE_PERSONAL_PHONE_SELECT(XPATH,getPropValue("EmployeePersonalPhoneSelect")),
	CUSTOMER_ID_EMAIL_ADDRESS(XPATH,getPropValue("customerIDEmailAddress")),
	PORTIN_OPTION(XPATH,getPropValue("portInDisconnectOption")),
	PORTIN_DISCONNECT(XPATH,getPropValue("portInDisconnect")),
	SELECTTYPE_LIST(XPATH,getPropValue("selectTypeList")),
	PROVIDER_ACCOUNT_NUMBER(XPATH,getPropValue("providerAcctNbr")),
	WEBHOSTING_YES(XPATH,getPropValue("webHostingYes")),
	WEBHOSTING_NO(XPATH,getPropValue("webHostingNo")),
	RESELLER_VALUE_INTERNET(XPATH,getPropValue("ResellerDropDownInternet")),
	RESELLER_VALUE_TV(XPATH,getPropValue("ResellerDropDownTv")),
	
	/*#################### INTERNET PRODUCT INFORMATION ######################*/
	
	SELECT_INTERNET_SERVICE(XPATH,getPropValue("selectInternetSvc")),
	INTERNET150_UNLIMITED(XPATH,getPropValue("internet150Unlimited")),
	INTERNET300_UNLIMITED(XPATH,getPropValue("internet300Unlimited")),
	INTERNET_15(XPATH,getPropValue("internet15")),
	INTERNET_300(XPATH,getPropValue("internet300")),
	EMPLOYEE_INTERNET300(XPATH,getPropValue("employeeInternet300")),
	INTERNET_50(XPATH,getPropValue("internet50")),
	FIBRE_25(XPATH,getPropValue("fibre25")),
	FIBRE_75(XPATH,getPropValue("fibre75")),
	FIBRE_150(XPATH,getPropValue("fibre150")),
	FIBRE_300(XPATH,getPropValue("fibre300")),
	FIBRE_250(XPATH,getPropValue("fibre250")),
	
	FREEDOM_INTERNET_150(XPATH,getPropValue("freedomInternet150")),
	INTERNET_HARDWARE(XPATH,getPropValue("internetHardware")),
	INTERNET150_RENT(XPATH,getPropValue("internet150Rent")),
	INTERNET150_HITRONRENT(XPATH,getPropValue("internet150HitronRent")),
	INTERNET_HITRON_BUY_BTN(XPATH,getPropValue("internetHitronBuyBtn")),
	INTERNET150_SERIAL_NBR_FIELD(XPATH,getPropValue("internet150SerialNbrField")),
	INTERNET150_SERIAL_NBR_FIELD_Staff(XPATH,getPropValue("internet150SerialNbrFieldStaff")),
	INTERNET_SRLNBR_VALIDATE(XPATH,getPropValue("internetSrlNbrValidate")),
	INTERNET_NOT_SELECTED(XPATH,getPropValue("internetNotSelected")),
	TEMP_SUSPEND_INTERNET(XPATH,getPropValue("tempSuspendInternet")),
	HARDWARE2(XPATH,getPropValue("hardware2")),
	INTERNET75_RENT(XPATH,getPropValue("internet75Rent")),
	INTERNET_EMAIL_WRENCH(XPATH,getPropValue("internetEmailWrench")),
	ADD_EMAIL_ADDRESS(XPATH,getPropValue("addEmailAddress")),
	EMAIL_TRANSFER_OPTIONS(XPATH,getPropValue("emailTransferOptions")),
	BRANCH_DROPDOWN_VALUE(XPATH,getPropValue("branchDropDownValue")),
	BRANCH_DROPDOWN_VALUE2(XPATH,getPropValue("branchDropDownValue2")),
	EMAIL_ADDRESS_AC_NBR(XPATH,getPropValue("emailAddressACNbr")), 
	
	BULK_FIBRE_300(XPATH,getPropValue("bulkfibre300")),
	BULK_FIBRE_150(XPATH,getPropValue("bulkfibre150")),
	BULK_FIBRE_25(XPATH,getPropValue("bulkfibre25")),
	BULK_PHONE_HARDWARE_DROPDOWN(XPATH,getPropValue("bulkphoneHardwareDropDown")),
	BULK_PERSONAL_PHONE(XPATH,getPropValue("bulkpersonalphone")),
	
    ADD_EMAIL_ADDRESS_INPUT(ID,getPropValue("addEmailAddressInput")),
	DELETE_EMAIL(ID,getPropValue("deleteEmailAddress")),
    EMAIL_VALIDATE(XPATH,getPropValue("emailValidate")),
	EMAIL_FIRST_NAME(ID,getPropValue("emailFirstName")),
	EMAIL_LAST_NAME(ID,getPropValue("emailLastName")),
	EMAIL_OK_BUTTON(XPATH,getPropValue("okButtonToClose")),
	EMAIL_RANGE_BUTTON(XPATH,getPropValue("emailRangeButton")),
    IP_ADDRESS_RANGE_BUTTON(XPATH,getPropValue("ipAddressRangeButton")),
    SIMCARD_SHAW_MOBILE_RANGE(XPATH,getPropValue("simCardShawMobileRange")),
    INT75_HITRON_RENT(XPATH,getPropValue("int75HitronRent")),
    INT75_HITRON_INPUT(XPATH,getPropValue("int75HitronInput")),
    INT75_HITRON_VALIDATE(XPATH,getPropValue("hitronValidate")),
    FIBER_MODEM_RENT_BTN(XPATH,getPropValue("fiberModemRentBtn")),
    FIBER_MODEM_INPUT(XPATH,getPropValue("fiberModemInput")),
    EMPLOYEE_INTERNET_75(XPATH,getPropValue("employeeInternet75")),
    PODS1PK_RENT(XPATH,getPropValue("pods1PKRent")),
	PODS1PK_INPUT(XPATH,getPropValue("pods1PKInput")),
	XPOD_3PK_RENT(XPATH,getPropValue("xPODRentBtn")),
	BLUECURVE_PODSV1_3PK_RENT_BTN(XPATH,getPropValue("BlueCurvePodsV13PKRentBtn")),
	BLUECURVE_PODSV1_INPUT(XPATH,getPropValue("BlueCurvePodsV1Input")),
	XPOD1_3PK_INPUT(XPATH,getPropValue("xPOD1Input")),
	XPOD1_VALIDATE_BUTTON(XPATH,getPropValue("xPOD1Validate")),
	XPOD2_3PK_INPUT(XPATH,getPropValue("xPOD2Input")),
	XPOD2_VALIDATE_BUTTON(XPATH,getPropValue("xPOD2Validate")),
	XPOD3_3PK_INPUT(XPATH,getPropValue("xPOD3Input")),
	XPOD3_VALIDATE_BUTTON(XPATH,getPropValue("xPOD3Validate")),
	
	/*#################### CONVERGED HARDWARE INFORMATION ######################*/
	
	CONVERGED_HARDWARE_PROD(XPATH,getPropValue("convergedHardwareProd")),
	CONVERGED_HARDWARE_WRENCH(XPATH,getPropValue("convergedHardware")),
    CONVERGED_HARWARE_RENT150(XPATH,getPropValue("convergedHardwareRent150")),
    CONVERGED_HARWARE_RENT150_SINGLE_ELEMENT(XPATH,getPropValue("singleElementConvergedHardwareRent150")),    
    CONVERGED_HARWARE_RENT75(XPATH,getPropValue("convergedHardwareRent75")),
	CONVERGED_HARDWARE_SERIAL_NUMBER_FIELD150(XPATH,getPropValue("convergedHardwareSerialNbr150")),
	CONVERGED_HARDWARE_SERIAL_NUMBER_FIELD150_SINGLE_ELEMENT(XPATH,getPropValue("singleElementConvergedHardwareSerialNbr150")),
	CONVERGED_HARDWARE_SERIAL_NUMBER_FIELD75(XPATH,getPropValue("convergedHardwareSerialNbr75")),
    CONVERGED_HARDWARE_SWAP(XPATH,getPropValue("ConvergedHardwareSwap")),
    TECHNICIAN_RADIO_BUTTON(XPATH,getPropValue("TechnicianRadioButton")),
    CONVERGED_HARDWARE_TECH_ID(XPATH,getPropValue("ConvergedHardwareTechId")),
    CONVERGED_HARDWARE_VALIDATE_TECH_ID(XPATH,getPropValue("ConvergedHardwareValidateTechId")),
    CONVERGED_HARDWARE_NEW_SERIAL_NO(XPATH,getPropValue("ConvergedHardwareNewSerialNo")),
    CONVERGED_HARDWARE_NEW_SERIAL_NO_VALIDATE(XPATH,getPropValue("ConvergedHardwareNewSerialNoValidate")),
    CONVERGED_HARDWARE_NEW_SERIAL_NO_OK_BUTTON(XPATH,getPropValue("ConvergedHardwareNewSerialNoOkButton")),
    
    FREEDOM_GATEWAY_WIFI_MODEM_RENT(XPATH,getPropValue("freedomGatewayWifiModem")),
    FREEDOM_GATEWAY_WIFI_MODEM_INPUT(XPATH,getPropValue("freedomGatewayWifiModemInput")),
    SEGMENT_FILTER1(XPATH,getPropValue("segmentFilter1")),
    SEGMENT_FILTER2(XPATH,getPropValue("segmentFilter2")),
    SEGMENT_FILTER3(XPATH,getPropValue("segmentFilter3")),
    SEGMENT_FILTER4(XPATH,getPropValue("segmentFilter4")),
    SEGMENT_FILTER5(XPATH,getPropValue("segmentFilter5")),
    FREEDOM_INTRNET150_DISCOUNT_INFO(XPATH,getPropValue("FreedomInternet150DiscountInfo")),
    TWO_YVP_INTERNET_TV_AGREEMENT_INFO(XPATH,getPropValue("2YVPInternetTVAgreementInfo")),
    FREEDOM_INTRNET150_DISCOUNT_INFO1(XPATH,getPropValue("FreedomInternet150DiscountInfo1")),
    FREEDOM_INTRNET150_DISCOUNT_CHECK_BOX(XPATH,getPropValue("FreedomInternet150DiscountCheckBox")),
	
	/*####################### TV PRODUCT INFORMATION #########################*/
	
	TEMP_SUSPEND_TV(XPATH,getPropValue("tempSuspendTv")),
	DIGITAL_CHANNEL_WRENCH(XPATH,getPropValue("digitalChannelWrench")),
	PICK10_PACK1(XPATH,getPropValue("Pick10Pack1")),
	PICK10_PACK1_WRENCH(XPATH,getPropValue("Pick10Pack1Wrench")),
	ASIDE(XPATH,getPropValue("ASide")),
	ESPN_CLASSIC(XPATH,getPropValue("ESPNClassic")),
	SPORTS_MAN(XPATH,getPropValue("sportsMan")),
	FIGHT_NETWORK(XPATH,getPropValue("FightNetwork")),
	MAKEFUL(XPATH,getPropValue("Makeful")),
	SILVER_SCREEN_CLASSICS(XPATH,getPropValue("SilverScreenClassics")),
	ONE_GET_FIT(XPATH,getPropValue("oneGetFit")),
	LOVE_NATURE(XPATH,getPropValue("LoveNature")),
	DEJA_VIEW(XPATH,getPropValue("Dejaview")),
	DOCUMENTRY(XPATH,getPropValue("documentry")),
	FOX_NEWS(XPATH,getPropValue("foxNews")),
	GSN_GAMESHOW_NETWORK(XPATH,getPropValue("GSNGameShowNetwork")),
	DIGITAL_CHANNEL_THEME(XPATH,getPropValue("DigitalChannelTheme")),
	ENT3MEDIUM_POTPOURRI2_MUSICPOP_CULTURE(XPATH,getPropValue("Ent3MediumPotpourri2MusicPopCulture")),
	TV_PROMOTION_PRICE_GUARANTEE(XPATH,getPropValue("tv24M2YVPLargeTVPriceGuarantee@$87")),
	MEDIUM_TV_PRICE_GUARANTE(XPATH,getPropValue("mediumTVPriceGuarante80")),
	SMALL_TV_PREBUILT(XPATH,getPropValue("smallTv")),
    SELECT_SHAW_DIRECT(XPATH,getPropValue("selectShawDirect")),
    SELECT_MOVING_VAL(XPATH,getPropValue("selectMovingVal")),
	DCX_RENT_SLNO(XPATH,getPropValue("DcxRentSlNo")),
	DCX3510_RENT_BTN(XPATH,getPropValue("Dcx3510RentBtn")),
	DCX3400_BUY_BTN(XPATH,getPropValue("DCX3400BuyBtn")),
	
	TV_DCX_WRENCH_BTN(XPATH,getPropValue("TVDCXWrenchbtn")),
	VALIDATE_DCX3510(XPATH,getPropValue("ValidateDCX3510")),
	TV_HARDWARE_WRENCH(XPATH,getPropValue("tvHardwareWrench")),
	DIGITAL_CLASSIC(XPATH,getPropValue("digitalClassic")),
	DIGITAL_BASIC(XPATH,getPropValue("digitalBasic")),
	TV_NOT_SELECTED(XPATH,getPropValue("TVNotSelected")),
	LIMITED_TV(XPATH,getPropValue("limitedTv")),
	SD_RENT(XPATH,getPropValue("sdRent")),
	THEME_BUTTON(XPATH,getPropValue("themeOkButton")),
	
	//BlueSky Box Hardware
	SHAW_BLUESKY_TV_BOX526_SLNO_INPUT(XPATH,getPropValue("RentShawBlueSkyTVbox526SlNoInput")),
	SHAW_BLUESKY_TV_SLNO_VALIDATE(XPATH,getPropValue("shawBlueSkySlrNbrValidate")),
	SHAW_BLUESKY_TV_PORTAL_416(XPATH,getPropValue("RentShawBlueSkyTVportal416")),
	SHAW_BLUESKY_TV_BOX416_SLNO_INPUT(XPATH,getPropValue("RentShawBlueSkyTVbox416SlNoInput")),
	SHAW_BLUESKY_TV_4KBOX530(XPATH,getPropValue("RentShawBlueSkyTV4Kbox(530)")),
	SHAW_BLUESKY_TV_4KBOX530_SLNO_INPUT(XPATH,getPropValue("RentShawBlueSkyTV4Kbox(530)Input")),
	
	//BlueSky Box Hardware Swap
	TV_HARDWARE_SWAP(XPATH,getPropValue("tvHardwareSwapButton")),
	TECH_BUTTON_FOR_SWAP(XPATH,getPropValue("techButtonForSwap")),
    TECH_ID_VALIDATE(XPATH,getPropValue("validateTechId")),
    TV_BLUESKY_HARDWARE_INPUT(XPATH,getPropValue("tvBox526HardwareInput")),
    TV_HARDWARE_VALIDATE_BTN(XPATH,getPropValue("tvHardwareValidateBtn")),
	PORTAL_TECH_RADIO_BTN(XPATH,getPropValue("portalTechRadioBtn")),

    MEDIUM_TV_PREBUILT(XPATH,getPropValue("mediumTV")), 
    TOTAL_TV(XPATH,getPropValue("totalTV")),
    NEWS_NEWS1(XPATH,getPropValue("newsNews1")),
    SPORTS_TSNPACK(XPATH,getPropValue("sportsTSNPack")),
    TIME_SHIFT(XPATH,getPropValue("timeShift")),
    MOVIES_VARIETY(XPATH,getPropValue("moviesVariety")),
    PICK10_PACK2(XPATH,getPropValue("Pick10Pack2")),
	PICK10_PACK2_WRENCH3(XPATH,getPropValue("Pick10Pack2Wrench3")),
	PICK10_PACK2_WRENCH2(XPATH,getPropValue("Pick10Pack2Wrench2")),
	ENT1_SUSPENSE(XPATH,getPropValue("Ent1Suspense")),
	HOLLYWOOD_SUITE(XPATH,getPropValue("hollywoodSuite")),
	
	SERVICE_AGREEMENT_PLAN_DD(XPATH,getPropValue("serviceAgreementPlanDD")),
	SERVICE_AGREEMENT_PLAN_VALUE(XPATH,getPropValue("serviceAgreementPlanvalue")),
	//METHOD_CONFIRMATION_DD(XPATH,getPropValue("methodOfConfirmationDD")),
	METHOD_CONFIRMATION_VALUE(XPATH,getPropValue("methodOfConfirmationValue")),
	ACCEPTANCE_ID_TEXT(XPATH,getPropValue("acceptanceIDText")),
	MULTICULTURAL_TAB(XPATH,getPropValue("multiculturalTab")),
	SOUTH_ASSIAN_PACK_OKBTN(XPATH,getPropValue("southAssianPackOkBtn")),
	SOUTHASIAN4_PACK1_CHECKBOX(XPATH,getPropValue("southAsian4Pack1CheckBox")),
	SOUTHASIAN4_PACK1_WRENCH(XPATH,getPropValue("southAsian4Pack1Wrench")),
	ATNASIAN_TELEVISION_NW_CHECKBOX(XPATH,getPropValue("ATNAsianTelevisionNetworkCheckBox")),
	AAPKA_COLOURS_CHECKBOX(XPATH,getPropValue("AapkaColorsCheckBox")),
	MH1_CHECKBOX(XPATH,getPropValue("mh1CheckBox")),
	ZEETV_CHECKBOX(XPATH,getPropValue("zeeTVCheckBox")),
	//SOUTHASIAN4_PACK1_OKBTN(XPATH,getPropValue("southAsian4Pack1OkBtn")),
	ONDEMAND_TAB(XPATH,getPropValue("onDemand")),
	SATURDAY_NYT_CHECKBOX(XPATH,getPropValue("saturdayNytCheckBox")),
	RETAIL_PICKUP_YES(XPATH,getPropValue("retailPickUpYes")),
	RETAIL_PICKUP_DROPDOWN(XPATH,getPropValue("retailPickupDropdown")),
	RETAIL_PICKUP_LIST_SELECTION(XPATH,getPropValue("retailPickupListSelection")),
	EMPLOYEE_TV(XPATH,getPropValue("employeeTV")),
	CONNECTING_FAMILIES(XPATH,getPropValue("connectingFamilies")),
	
	ONDEMAND_FEATURES_DROPDOWN(XPATH,getPropValue("onDemandFeaturesdropdown")),
	APP_MUS_OPTION(XPATH,getPropValue("APP/MUSoption")),
	
	BULK_TOTAL_TV(XPATH,getPropValue("bulkTotalTV")),
	BULK_LEGACY_POPULAR_TV(XPATH,getPropValue("bulklegacyPopularTV")),
	BULK_DIGITAL_BASIC_TV(XPATH,getPropValue("bulkdigitalBasicTV")),
	
	/*################### Appointments, dates & reasons Tab ########################*/
	SELF_CONNECT_YES_RADIO_BTN(ID,getPropValue("SelfConnectYesRadioBtn")),
	SELF_CONNECT_NO_RADIO_BTN(ID,getPropValue("SelfConnectNoRadioBtn")),
	TECH_APPOINMENT_YES(XPATH,getPropValue("TechAppointmentYes")),
	TECH_APPOINMENT_NO(XPATH,getPropValue("TechAppointmentNo")),
	SMS_NBR_FIELD(XPATH,getPropValue("custOrderSMSNbrField")),
	SMS_NBR_CHECK_BOX(XPATH,getPropValue("custOrderSMSNbrCheckBox")),
	CHANGEAUTHORIZEDBY(XPATH,getPropValue("changeAuthorizedBy")),
	RETAIL_PICKUP_RADIO_BTN(XPATH,getPropValue("retailPickUpRadioBtn")),
	MAIL_OUT_RADIO_BTN(XPATH,getPropValue("mailOutRadioBtn")),
	EXISTING_HW_PREMISEMOVE_RADIO_BTN(XPATH,getPropValue("existingHWPremiseMoveRadioBtn")),
	HARDWARE_DROPOFF_RADIO_BTN(XPATH,getPropValue("hardwareDropOffRadioBtn")),
	ACTIVCATION_ON_CNFM_MSG(XPATH,getPropValue("activationOnCnfmMsg")),
	RETAILPICKUP_VALIDATION_MSG(XPATH,getPropValue("retailPickUpValidationMsg")),
	EFFECTIVE_DATE_CONFIRMATION(XPATH,getPropValue("effectiveDateCnfm")),
	VALIDATE_SALES_REPRESENTATIVE(XPATH,getPropValue("validateSalesRepresantative")),
	REMINDER_TEXT(XPATH,getPropValue("remindertext")),
	

	/****************** CUSTOMER OE PAGE INFORMATION *********************/
	
	OPERATIONS_TAB(XPATH,getPropValue("operationsTab")),
	SNOWBIRD(XPATH,getPropValue("snowBirdOption")),
	SKIP(XPATH,getPropValue("skip")),
	ENABLE_SNOWBIRD(XPATH,getPropValue("enableSnowBird")),
	SNOWBIRD_START_DATE(XPATH,getPropValue("snowBirdStartDate")),
	SNOWBIRD_END_DATE(XPATH,getPropValue("snowBirdEndDate")),
	ORDER_WEB_TABLE(ID,getPropValue("orderWebTable")),
	ORDER_MANAGEMENT(XPATH,getPropValue("orderManagement")),
	
	BILLING_ADDRESS(XPATH,getPropValue("billingAddress")),
	MORE(XPATH,getPropValue("more")),
	DUE_DATE_CHECK_BOX(XPATH,getPropValue("duedateCheckBox")),
	CONFIRM_PROMOTION(XPATH,getPropValue("confirmPromotion")),
	SERVICE_AGREEMENT_PLAN(XPATH,getPropValue("serviceAgreementPlan")),
	METHOD_OF_CONFIRMATION(XPATH,getPropValue("methodOfConfirmation")),
	CONFIRMATION_ADDITIONAL(XPATH,getPropValue("confirmAdditional")),
	CLOSE_BUTTON(XPATH,getPropValue("closeButton")),
	GENERATE_AGREEMENT_NO(XPATH,getPropValue("generateAgreementNo")),
	DELETE_HARDWARE(XPATH,getPropValue("deleteHardware")),
	DELETE_CONVERGED_HARDWARE(XPATH,getPropValue("deleteConvergedHardware")),
	REMOVE_CONFIRM_YES(XPATH,getPropValue("removeConfirmYes")),
	NEXT_MONTH_ARROW(XPATH,getPropValue("nextMonthArrow")),
	PREVIOUS_MONTH_ARROW(XPATH,getPropValue("previousMonthArrow")), 
	NEXT_MONTH_SNOWBIRD(XPATH,getPropValue("nextMonthSnowBird")),
	PREV_MONTH_SNOWBIRD(XPATH,getPropValue("prevMonthSnowBird")),
    FIRST_DATE(XPATH,getPropValue("firstDateOfMonth")),
    DIGITAL_CHANNEL_OK(XPATH,getPropValue("DigitalChannelOk")),
    PICK_10_OK_BUTTON(XPATH,getPropValue("pick10OkBtn")),
    TODO_LIST_CHECKBOX(XPATH,getPropValue("todoListChechBox")),
	DEFAULT_INSTALLATION_FEE_CHECKBOX(XPATH,getPropValue("defaultInstallationFeeCheckBox")),
	INSTALLATIONFEE(XPATH,getPropValue("installationFee")),
	MOCAFILTERYES(XPATH,getPropValue("Mocafilteryes")),
	MOCAFILTERNO(XPATH,getPropValue("Mocafilterno")),
	APPOINTMENT(LINK_TEXT,getPropValue("appointment")),
	//IS_TECH_ASSIST_DROPOFF_NO(XPATH,getPropValue("isTechAssistDropOffNo")),
	//IS_TECH_ASSIST_DROPOFF_YES(XPATH,getPropValue("isTechAssistDropOffYes")),
	TECH_APPOINTMENT_DATE(XPATH,getPropValue("techAppointmentDate")),
	DIRECT_FULFILLMENT_BUTTON_NO(ID,getPropValue("directFulfillmentButtonNo")),
	RETAIL_PICKUP_BUTTON_NO(XPATH,getPropValue("retailPickupButtonNo")),
	CO_FOR_SHIPPING(XPATH,getPropValue("coForShipping")),
	DELIVERY_INSTRUCTION_INPUT(XPATH,getPropValue("deliveryInstructionInput")),
	
	MOCA_FILTER_RADIO_BTN(ID,getPropValue("mocaFilterRadioBtn")),
	SELECT_PREMISE_MOVE_DATE(XPATH,getPropValue("selectPremiseMoveDate")),
	PREMISE_MOVE_SERVICE_NUMBER(ID,getPropValue("premiseMoveServiceNumber")),
	PREMISE_MOVE_DISCONNECTION_DATE(XPATH,getPropValue("premiseMoveDisconnectionDate")),
	ACTIVATION_DATE(XPATH,getPropValue("ActivationDate")),
	FORCE_APPOINTMENT_CHECKBOX(XPATH,getPropValue("selectManualAppointment")),
	CLICK_CALENDAR(XPATH,getPropValue("clickCalendar")),
	CLICK_REFRESH(XPATH,getPropValue("refreshButton")),
	SCHEDULE_ANOTHER_APPOINTMENT(XPATH,getPropValue("AnotherAppointment")),
	CANCEL_ORDER(XPATH,getPropValue("cancelOrder")),
	CANCEL_TRANSFER(XPATH,getPropValue("cancelTransfer")),
	CANCEL_YES(XPATH,getPropValue("cancelYes")),
	OK_BTN_TO_CLOSE(XPATH,getPropValue("okBtnToClose")),
	REASSIGN_CHECKBOX(XPATH,getPropValue("reAssignCheckBox")),
	PROMOTION_AND_COUPON_SELECTION(XPATH,getPropValue("promotionAndCouponSelection")),
    YVP_INTERNET_TV_AGREEMENT(XPATH,getPropValue("2YVPInternetTVAgreement")),
    GENERATE_AGREEMENT(XPATH,getPropValue("generateAgreementYes")),
    SERVICE_AGREEMENT_BTN(XPATH,getPropValue("serviceAgreementBtn")),
    SERVICE_AGREEMENT_DROPDOWN(XPATH,getPropValue("serviceAgreementDropdown")),
    SERVICE_CONFIRMATION_DROPDOWN(XPATH,getPropValue("methodOfConfirmationDropDown")),
    ACCEPTANCE_ID(XPATH,getPropValue("acceptanceId")),
    SERVICE_AVILABILITY(XPATH,getPropValue("serviceAvailability")),
    CDI(XPATH,getPropValue("cdi")),
    CDI_ACCOUNT_TYPE_BTN(XPATH,getPropValue("cdiAccountTypeBtn")),
    CDI_ACCOUNT_SUB_TYPE_BTN(XPATH,getPropValue("cdiAccountSubTypeBtn")),
    LOCATION_DROP_TYPE(XPATH,getPropValue("locationDropType")),
    BILLING_PREFERENCES_MORE(XPATH,getPropValue("billingPreferencesMore")),
    ADD_TEX_EXEMPTION_BTN(ID,getPropValue("addTaxExemptionBtn")),
    BILL_ONTHIS_DAY_OF_MONTH(XPATH,getPropValue("billOnThisDayOfTheMonth")),
    GST_RADIO_BTN(XPATH,getPropValue("gstRadioBtn")),
    PST_RADIO_BTN(XPATH,getPropValue("pstRadioBtn")),
    HST_RADIO_BTN(XPATH,getPropValue("hstRadioBtn")),
    EXEMPTION_TYPE(XPATH,getPropValue("exemptionType")),
    FIRST_NATIONS_ON_RESERVE(XPATH,getPropValue("firstNationsONReserve")),
    TAX_JURISDITION_TYPE(XPATH,getPropValue("taxjurisdictionType")),
    TAX_SELECT_CANADA(XPATH,getPropValue("taxSelectCanada")),
    TAX_REFERENCE_ID(XPATH,getPropValue("taxReferenceID")),
    AGREEMENT_BTN_CLOSE(XPATH,getPropValue("agreementBtnClose")),
	REVIEW(XPATH,getPropValue("review")),
	SEND_SIMMARY_RADIO_BTN_NO(XPATH,getPropValue("sendSummaryRadioBtnNo")),
	FINISH(XPATH,getPropValue("finish")),
	FINISHDISABLE(XPATH,getPropValue("finishDisabled")),
	DIRECT_FULFILLMENT_BUTTON_YES(XPATH,getPropValue("directFulfillmentButtonYes")),
	SPECIAL_SHIPPING_ADDRESS_BTN(XPATH,getPropValue("specialShippingAddressBtn")),
	SPECIAL_SHIPPING_ADDRESSL1(XPATH,getPropValue("specialShippingAddressL1")),
	SPECIAL_SHIPPING_CITY_TOWN(XPATH,getPropValue("specialShippingCityTown")),
	SPECIAL_SHIPPING_ADDRESS_CODE(XPATH,getPropValue("specialShippingAddressCode")),
	CONTACT_NUMBER(XPATH,getPropValue("contactNumber")),
	OPT_OUT(XPATH,getPropValue("OptOut")),
	BUZZER_CODE(XPATH,getPropValue("BuzzerCode")),
	GENERATE_AGREEMENT_YES(XPATH,getPropValue("generateAgreementYes")),
	MAILLING_ADDRESS_RADIO_BTN(XPATH,getPropValue("mailingAddressRadioBtn")),
	HOUSE_NUMBER(XPATH,getPropValue("houseNumber")),
	SUFFIX_NUMBER(XPATH,getPropValue("suffixNumber")),
	STREET_ADDRESS(XPATH,getPropValue("streetAddress")),
	PORT_TEXT(XPATH,getPropValue("portText")),
	TODO_TEXT(XPATH,getPropValue("todoText")),
	RADIO_BTN(XPATH,getPropValue("radioBtn")),
	PHONE_OPT_OUT(XPATH,getPropValue("phoneoptout")),
	STREET_TYPE_LIST(XPATH,getPropValue("streetTypeList")),
	STREET_TYPE(XPATH,getPropValue("streetType")),
	DIRECTIONS_LIST(XPATH,getPropValue("directionsList")),
	DIRECTIONS(XPATH,getPropValue("directions")),
	MAILING_QUARDRANT_LIST(XPATH,getPropValue("mailingQuadrantList")),
	MAILING_QUARDRANT(XPATH,getPropValue("mailingQuadrant")),
	UNIT_INPUT(XPATH,getPropValue("unitInput")),
	CITY_TOWN_LIST(XPATH,getPropValue("cityTownList")),
	CITY_TOWN_VALUE(XPATH,getPropValue("cityTownValue")),
	POSTAL_CODE(XPATH,getPropValue("postalCode")),
	SEARCH_BUTTON(XPATH,getPropValue("searchButton")),
	SEARCH_BUTTON1(XPATH,getPropValue("searchButton1")),
	SELECT_BUTTON(XPATH,getPropValue("selectButton")),
	CHANGE_PH_NBR_BTN(XPATH,getPropValue("changePhNbrBtn")),
	RETRIEVE_ORDER_INFORMATION(XPATH,getPropValue("retrieveOrderInfomation")),
	SHAW_SERVICE_REQUESTED_YES(XPATH,getPropValue("shawServiceRequestedYes")),
    SELECT_ADDRESS(XPATH,getPropValue("selectAddress")),
    OLD_HOUSE_NBR_TXT(XPATH,getPropValue("oldHouseNbrTxt")),
    OLD_STREET_NAME(XPATH,getPropValue("oldStreetName")),
    OLD_CITY(XPATH,getPropValue("OldCity")),
    OLD_POSTAL_CODE(XPATH,getPropValue("oldPostalCode")),
	ACCOUNT_TYPE_RESIDENTIAL(XPATH,getPropValue("accountTypeResidential")),
	ACCOUNT_TYPE_STAFF(XPATH,getPropValue("accountTypeStaff")),
	MAILING_ADDRESS_NBR(ID,getPropValue("mailingAddressNbr")),
	MAILING_ADDRESS_SUFFIX(ID,getPropValue("mailingAddressSuffix")),
	MAILING_ADDRESS_STREET_NAME(ID,getPropValue("mailingAddressStreetName")),
	MAILING_ADDRESS_STREET_TYPE(XPATH,getPropValue("mailingAddressStreetType")),
	MAILING_ADDRESS_STREET_TYPE_VALUE(XPATH,getPropValue("mailingAddressStreetTypeValue")),
	MAILING_ADDRESS_DIR_DORPDOWN(XPATH,getPropValue("mailingAddressDirDropDown")),
	MAILING_ADDRESS_DIR_VALUE(XPATH,getPropValue("mailingAddressDirValue")),
	MAILING_ADDRESS_QUADRANT_DD(ID,getPropValue("mailingAddresQuadrantDd")),
	MAILING_ADDRESS_QUADRANT_VALUE(XPATH,getPropValue("mailingAddresQuadrantValue")),
	MAILING_ADDRESS_APT_UNIT(ID,getPropValue("mailAddressAptUnit")),
	MAILING_ADDRESS_CITY(XPATH,getPropValue("mailingAddressCity")),
	MAILING_ADDRESS_CITY_VALUE(XPATH,getPropValue("mailingAddressCityValue")),
	MAILING_ADDRESS_POSTAL_CODE(ID,getPropValue("mailingAddressPostalCode")),
	MAILING_ADDRESS_CHECK(ID,getPropValue("mailingAddressCheck")),
	CLICK_OK_BUTTON(XPATH,getPropValue("okButton")),
	BUNDLES_LINK(XPATH,getPropValue("bundlesLink")),
	ISED_PIN_VALUE(XPATH,getPropValue("isedPin")),
	NBR_OF_RETRY(XPATH,getPropValue("nbrOfRetry")),
	TIME_INCREAMENT(XPATH,getPropValue("timeIncreament")),
	SLEEP_INTERVAL_SECOND(XPATH,getPropValue("sleepIntervalSecond")),
	SET_PREFERRED_PAYMENT_BTN(XPATH,getPropValue("preferredPaymentBtn")),
	BILL_CYCLE_INC_BTN(XPATH,getPropValue("billCycleIncBtn")),
	
	/****************** CUSTOMER OM PAGE INFORMATION *********************/
	
	GENERIC_SEARCH(XPATH,getPropValue("genericSearch")),
	SEACH_BUTTON(XPATH,getPropValue("searchButton")),
	REINSTATE_PAST_RESOURCE(XPATH,getPropValue("reinstatePastResource")),
	REINSTATE_START_NEW_ORDER(XPATH,getPropValue("reinistateStartNew")),
	RETRIVE_ORDER_INFORMATION(XPATH,getPropValue("retriveOrderInformation")),
    CLECOPS_FILTER(XPATH,getPropValue("clecOpsFilter")),
    CLECOPS_SEARCH_BOX(XPATH,getPropValue("clecOpsSearchBox")),
    APPLY_FILTER(XPATH,getPropValue("applyFilter")),
    CLEC_OPS_USER_NAME(XPATH,getPropValue("clecOpsUserName")),
    GROUP_TASKS_TAB(XPATH,getPropValue("groupTasksTab")),
    INITIATE_LINE_ACTIVATION(XPATH,getPropValue("initiateLineActivation")),
	LSC_COMPLETE_BUTTON(XPATH,getPropValue("lSCCompleteButton")),
	ACCOUNTNUMBER(XPATH,getPropValue("accountNbr")),
	ORDERNUMBER(XPATH,getPropValue("orderNbr")),
	PHONENUMBER(XPATH,getPropValue("phoneNbr")),
	CUSTINFOSTAT(XPATH,getPropValue("custInfoStat")),
	BILLINGACCOUNTSTAT(XPATH,getPropValue("billingAcctStat")),
	ACCOUNT_LINK(XPATH,getPropValue("acctLink")),
	ORDER_MGMT_STAT(XPATH,getPropValue("ordermgmtstat")),
	SWAP_HARDWARE(XPATH,getPropValue("SwapHardware")),
    TECH_RADIO_BTN(XPATH,getPropValue("techRadioBtn")),
    TECHNICIAN_ID(XPATH,getPropValue("technicianId")),
    VALIDATE_TECH_ID(XPATH,getPropValue("ValidateTechId")),
    SWAP_SL_NO(XPATH,getPropValue("SwapSlno")),
    VALIDATE_SWAP_SLNO(XPATH,getPropValue("ValidateSwapSlno")),
    LSC_RESPONSEJOB_STATUS(XPATH,getPropValue("lscResponseJobStatus")),
    LSC_RESPONSE_JOB_ITEM(XPATH,getPropValue("lscResponseJobItem")),
    LSE_RESPONSE_PAUSE_BTN(XPATH,getPropValue("lseResponsePauseBtn")),
    LSE_RESPONSE_RESUME_BTN(XPATH,getPropValue("lseResponseResumeBtn")),
    PORTIN_DISCONNECT_SELECTION(XPATH,getPropValue("portinDisconnectSelection")),
    PORTIN_DISCONNECT_BTN(XPATH,getPropValue("portinDisconnectBtn")),
    TYPE_OF_LOBS(XPATH,getPropValue("typeOfLOBs")),
	LOBS_LIST_SELECT_PHONE(XPATH,getPropValue("lobsListSelectPhone")),
	PORTING_PHNBR_FIELD(XPATH,getPropValue("portingphNbrField")),
	APPLY_CHANGES(XPATH,getPropValue("applyChanges")),
    IMMEDIATE_EMAIL_LINK(XPATH,getPropValue("immediateEmailLink")),
    IMMEDIATE_HARDWARE_LINK(XPATH,getPropValue("immediateHardwareLink")),
    IMMEDIATE_REPROVISION_BTN(XPATH,getPropValue("immediateReprovisionBtn")),
    IMMEDIATE_REPROVISION_BTN2(XPATH,getPropValue("immediateReprovisionBtn2")),
    IMMEDIATE_REPROVISION_BTN_MSG(XPATH,getPropValue("immediateReprovisionBtnMsg")),
    IMMEDIATE_UNDO_REPROVISION_BTN(XPATH,getPropValue("immediateundoReprovisionBtn")),
    CREATE_TRANSFER_EMAIL_BTN(XPATH,getPropValue("createTransferEmailBtn")),
    
    IMMEDIATE_ADD_EMAIL_ADDRESS(XPATH,getPropValue("immediateaddEmailAddress")),
    IMMEDIATE_EMAIL_ADDRESS(XPATH,getPropValue("immediateemailAddress")),
    IMMEDIATE_EMAIL_VALIDATE(XPATH,getPropValue("immediateEmailValidate")),
    IMMEDIATE_FIRST_NAME(XPATH,getPropValue("immediateFirstName")),
    IMMEDIATE_LAST_NAME(XPATH,getPropValue("immediateLastName")),
    IMMEDIATE_PHONE_FEATURE(XPATH,getPropValue("immediatePhoneFeature")),
   
    COLLEECT_CALLS_DISABLE_RADIO_BTN(XPATH,getPropValue("immediateCollectCallsRadioBtn")),
    BILL_TO_3RD_ENABLE_RADIO_BTN(XPATH,getPropValue("immediateBillTo3rdRadioBtn")),
    OPERATOR_REQEST_ENABLE_RADIO_BTN(XPATH,getPropValue("immediateOperatorRequset")),
    DIRECTORY_ASSISTANCE_DISABLE_RADIO_BTN(XPATH,getPropValue("immediateDirectoryAssistance")),
    IMMEDIATE_CHANGE_AUTHORIZED_TEXT(ID,getPropValue("immediateChangeAuthorized")),
    IMMEDIATE_CUSTOMER_INFO(XPATH,getPropValue("immediateDirectoryAssistance")),
    CLEC_OPS(XPATH,getPropValue("clecops")),
	ERRONEOUS_PROCESS_TASK(XPATH,getPropValue("erroneousProcessesTask")),
	ERRORS_TAB(XPATH,getPropValue("errorsTab")),
	ERRORS_IN_FFM_SERVICE_CALL(XPATH,getPropValue("errorInFFMServiceCall")),
	PARAMETERS_TAB(XPATH,getPropValue("parametersTab")),
	
	/************************ PRAMOTIONS & COUPONS INFORMATION *********************/
	
	ACCOUNT_VIEW_TAB(XPATH,getPropValue("accountViewTab")),
	ROLE_VIEW_TAB(XPATH,getPropValue("roleViewTab")),
	
    PROMOTIONS_LINK(XPATH,getPropValue("promotionLink")),
	PROMOTION_COUPONS_DROPDOWNN(XPATH,getPropValue("promotionCouponsDropdown")),
	FUNCTIONAL_DROPDOWNN(XPATH,getPropValue("functionalDropDown")),
	FUNCTIONAL_OPTIONS_DROPDOWNN(XPATH,getPropValue("functionaloptions")),
	GENERAL_DROPDOWNN(XPATH,getPropValue("Generaldropdown")),
	INBOUND_SALES_DROPDOWNN(XPATH,getPropValue("Inboundsalesdropdown")),
	RETAIL_DROPDOWNN(XPATH,getPropValue("retaildropdown")),
	INTERNET_PRODUCT_BTN(XPATH,getPropValue("internetproductbtn")),
	TV_PRODUCT_BTN(XPATH,getPropValue("TVproductBtn")),
//	STARTWOYVP_INTERNET_TVAGREEMENT(XPATH,getPropValue("*2YVPInternetTVAgreementchckbox")),
	TWENTYFOUR_M_TWOYVP_FIBRE_150_PRICEGURANTEE95_CHECK_BOX(XPATH,getPropValue("24M2YVPFibre150PriceGuarantee$95chckbox")),
	TWENTYFOUR_M_TWOYVP_TOTAL_TV_PRICE_GUARANTEE_95_CHECK_BOX(XPATH,getPropValue("24M2YVPtotalTVpriceguarantee95")),
	TWOYVP_INTERNET_TVAGREEMENT(XPATH,getPropValue("2YVPInternetTVAgreement")),
	TWENTYFOUR_M_INT_50PROMO_70(XPATH,getPropValue("24MInternet50Promo70")),
	TYVP_INTERNET300_PG85(XPATH,getPropValue("24M2YVPInternet300PG@$85")),
	TV_PROMOTION_BTN(XPATH,getPropValue("tvPromotionsBtn")),
	DIGITAL_CLASSIC_TV_PRICE_GUARANTE(XPATH,getPropValue("digitalClassicPriceGuarante")),
	TWOYVP24M_LIMITEDTV_PRICEGURANTEE(XPATH,getPropValue("24M2YVPLimitedTVPriceGuarantee$25")),
	TWOYVP24M_SMALLTV_PRICEGURANTEE(XPATH,getPropValue("24M2YVPSmallTVPriceGuarantee$60")),
	TWOYVP24M_DIGITAL_CLASSICTV_PRICEGURANTEE90(XPATH,getPropValue("24M2YVPDigitalClassicTVPriceGuarantee$90")),
	TWOYVP24M_FIBRE_75_PRICEGURANTEE85(XPATH,getPropValue("24M2YVPFibre75PriceGuarantee$85")),
	TWOYVP24M_TOTALTV_PRICEGURANTEE95(XPATH,getPropValue("24M2YVPTotalTVPriceGuarantee@$95")),
	TWOYVP24M_FIBRE_300_PRICEGURANTEE100(XPATH,getPropValue("24M2YVPFibre300PriceGuarantee@$100")),
	
	TWENTYFOURM_INTERNET_100PROMO92(XPATH,getPropValue("24MInternet100Promo92")),
	PHONE_PROMOTION_BTN(XPATH,getPropValue("PhonePromotionBtn")),
	THREEM_PERSONAL_PHONE15(XPATH,getPropValue("3MPersonalPhone15")),
	PERSONAL_PHONE_PG20(XPATH,getPropValue("personalPhonePG20")),
	
	LARGETV_PREBUILT_PRICE_GUARANTE95(XPATH,getPropValue("largeTVPrebuiltPriceGuarantee95")),
	LARGETV_PREBUILT_PROMO10(XPATH,getPropValue("largeTVPrebuiltPromo$10")),
	OK_BUTTON_TO_CLOSE(XPATH,getPropValue("okButtonToClose")),
	OK_BUTTON_TO_CLOSE_PROMOTION(XPATH,getPropValue("okButtonToClosePromotion")),
	PROMOTION_INFO_BTN(XPATH,getPropValue("promotioninfoBtn")),
	CONTRACTED_UNIT(XPATH,getPropValue("ContractedUnit")),
	PROMOTION_CLOSE_BTN(XPATH,getPropValue("promotionCloseBtn")),
	BULK_FIBER_300_WRENCH_BTN(XPATH,getPropValue("bulkfiber300wrenchBtn")),
	BULK_FIBER_300_PRICE_INPUT(XPATH,getPropValue("bulkfiber300priceinput")),
	BULK_FIBER_150_WRENCH_BTN(XPATH,getPropValue("bulkfiber150wrenchBtn")),
	BULK_FIBER_25_WRENCH_BTN(XPATH,getPropValue("bulkfiber25wrenchBtn")),
	BULK_HARDWARE(XPATH,getPropValue("bulkhardware")),
	BULK_HARDWARE_RENTAL_BLUE_CURVE_UPARROW(XPATH,getPropValue("bulkrentalBluecurveUparrow")),
	
	RENTAL_BLUE_CURVE348_UPARROW(XPATH,getPropValue("rentalBluecurve348Uparrow")),
	
	BULK_INTERNET_HARDWARE_OK_BTN(XPATH,getPropValue("bulkinternethardwareOkBtn")),
	BULK_TOTAL_TV_WRENCH_BTN(XPATH,getPropValue("bulktotaltvwrenchBtn")),
	BULK_TOTAL_TV_PRICE_INPUT(XPATH,getPropValue("bulktotaltvPriceInput")),
	BULK_LEGACY_POPULAR_TV_WRENCH_BTN(XPATH,getPropValue("BulkLegacyPopularTVwrenchBtn")),
	BULK_DIGITAL_BASIC_WRENCH_BTN(XPATH,getPropValue("BulkDigitalBasicwrenchBtn")),
//	BULK_HARDWARE(XPATH,getPropValue("bulkhardware")),
	BULK_HARDWARE_RENTAL_BLUE_CURVE_TV_UPARROW(XPATH,getPropValue("bulkrentalBluecurveTVUparrow")),
	
	RENTAL_BLUE_CURVE_TV_4K_UPARROW(XPATH,getPropValue("rentalBluecurveTV4kUparrow")),
	
	BULK_RENTAL_DCT_700_UPARROW(XPATH,getPropValue("RentalDCT700Uparrow")),
	BULK_TV_HARDWARE_OK_BTN(XPATH,getPropValue("bulkTVhardwareOkBtn")),
	XG1V3_BLUE_CURVE_TV_PLAYER_RENTAL_UPARROW(XPATH,getPropValue("XG1v3bluecurveTVplayerRentalUparrow")),
	BULK_PERSONAL_PHONE_WRENCH_BTN(XPATH,getPropValue("bulkPersonalPhonewrenchBtn")),
	RENTAL_PHONE_TERMINAL_UPARROW(XPATH,getPropValue("rentalPhoneTerminalUparrow")),
	
	TENANT_PRODUCT_CATEGORY_LIST(XPATH,getPropValue("tenantproductcategoryList")),
	TENANT_DROPDOWN(XPATH,getPropValue("tenantdropdown")),
	
	LIFETIME_DCX_DISCOUNT(XPATH,getPropValue("lifeTimeDCXDiscount")),
	TWENTYFOURM_PRICE_GUARANTEE95(XPATH,getPropValue("24M2YVPI300PriceGuarantee@$95")),
	TWENTYFOURM_PRICE_GUARANTEE90(XPATH,getPropValue("24M2YVPI300PriceGuarantee@$90")),
	TWENTYFOURM_FIBRE150_PRICE_GUARANTEE95(XPATH,getPropValue("24M2YVPI150PriceGuarantee@$95")),
	
	DCT_700_DISCOUNT(XPATH,getPropValue("DCT700Discount")),
	SERVICE_LOCATION_ADDRESS(XPATH,getPropValue("serviceLocationAddress")),
	PHONE_NBR_WRENCH(XPATH,getPropValue("phoneNbrWrench")),
	
	TWO_YVP_INTERNET_TV_AGGREEMENT_METHOD(XPATH,getPropValue("2YVPInternetTVAgreementMethod")),
	TWO_YVP_INTERNET_TV_AGGREEMENT_METHOD1(XPATH,getPropValue("2YVPInternetTVAgreementMethod1")),
	INTERNET_PROMOTION_BTN(XPATH,getPropValue("internetPramotionsBtn")),
	INTERNET_PROMOTION_SIXTH(XPATH,getPropValue("internet6M2YVPI75Promo@$50")),
	INTERNET_PROMOTION_FIFTH(XPATH,getPropValue("internet24M2YVPI75PriceGuarantee@$85")),
	INTERNET_PROMOTION(XPATH,getPropValue("12MInternet100Promo@$60(S)")),
	PHONE_PROMOTION_SIXTH(XPATH,getPropValue("phone3MPersonalPhone@$15")),
	TV_PROMOTION_THIRD(XPATH,getPropValue("tv24M2YVPLargeTVPriceGuarantee@$87")),
	TV_PICK_OPTION_WRENCH(XPATH,getPropValue("tvPickOptionWrench")),
	ENT3_POTPOURRI2_RADIO_BTN(XPATH,getPropValue("Ent3Potpourri2RadioBtn")),
	THREEM_LARGETV55(XPATH,getPropValue("3MLargeTV@$55")),
	SHAW_GATEWAY_HDPVR_524_525_SWAP(XPATH,getPropValue("ShawGatewayHDPVR524/525Swap")),
	DCX_3200M_501_506_SWAP(XPATH,getPropValue("DCX3200M501/506Swap")),
	DCT_700_Swap(XPATH,getPropValue("DCT700swap")),
	TV_MOXI_RADIO_TECH_BTN(XPATH,getPropValue("tvMOXIRadioTechBtn")),
	
	METHOD_CLOSE(XPATH,getPropValue("methodClose")),
	INTERNET_PRODUCT_PROMO(XPATH,getPropValue("internetPramotionsBtn")),
	TWO_YVP_INTERNET_TV_AGGREEMENT(XPATH,getPropValue("2YVPInternetTVAgreement")),
	TWO_YVP_PRICE_GURANTEE(XPATH,getPropValue("24M2YVPPriceGuarantee")),
	
	PHONE_PRODUCT_PROMO(XPATH,getPropValue("PhoneProductPromo")),
	TWO_YVP_PERSONAL_PHONE_PRICE_GURANTEE(XPATH,getPropValue("2YVPersonalPhonePriceGurantee")),
	TAWELM_2YVP_NETFLIX_PROMO(XPATH,getPropValue("12M2YVPNetFlixPromo")),
	TWOYVP_INTERNET_AGREEMENT1(XPATH,getPropValue("2YVPInternetAgreement")),
	TWOYVP_INTERNET_AGREEMENT(XPATH,getPropValue("*2YVPInternetAgreement")),
	TWOYVP_INTERNET_AGREEMENT2(XPATH,getPropValue("*2YVPInternetAgreement2")),
	PROMO175_$70(XPATH,getPropValue("12M2YVPI75Promo@$70")),
	TWOYVP_INTERNET100_PRICE_GUARANTEE72(XPATH,getPropValue("24M2YVPInt100PriceGuarentee72")),
	TYVP_INTERNET_TV_AGREEMENT(XPATH,getPropValue("*2YVPInternetTVAgreement")),
	MTYVP_LARGETV_PRICE_GUARANTEE(XPATH,getPropValue("24M2YVPLargeTVPriceGuarantee@$87")),
	LIFETIME_1STDCX3200_RENT_DISCOUNT(XPATH,getPropValue("Lifetime1stDCX3200MRentalDiscount")),
	MTYVP_LARGETV_$55(XPATH,getPropValue("6M2YVPLargeTV@$55")),
	
	ONEY_TWOP_BULKMASTER_TERMRATE_AGREEMENT(XPATH,getPropValue("1Y2PBulkMasterTermRateAgreement")),
	ONEY_ONEP_TV_BULKMASTER_TERMRATE_AGREEMENT(XPATH,getPropValue("1Y1PTVBulkMasterTermRateAgreement")),
	ONEY_THREEP_BULKMASTER_TERMRATE_AGREEMENT(XPATH,getPropValue("1Y3PBulkMasterTermRateAgreement")),
	
	
	WARNING_POPUP_OK_BTN(XPATH,getPropValue("warningpopupOkbtn")),
	
	
    /***********************************************************
 	    TV Hardware Rent button and Serial Number Input Box
     **********************************************************/
	
	RENT_DCT_700(XPATH,getPropValue("DCT700(599/594)")),
	DCT_700_SLNO_INPUT(XPATH,getPropValue("DCT700(599/594)SlNoInput")),
	DCT_700_SLNO_INPUT1(XPATH,getPropValue("DCT700(599/594)SlNoInput1")),
	
	RENT_DCX_3200M(XPATH,getPropValue("DCX3200M(506/501)")),
	DCX_3200M_SLNO_INPUT(XPATH,getPropValue("DCX3200M(506/501)SlNoInput")),
	DCX_3200M_SLNO_INPUT1(XPATH,getPropValue("DCX3200M(506/501)SlNoInput1")),
	
	RENT_DCX_3200_HDGUIDE(XPATH,getPropValue("DCX3200HDGuide(518/517/516/511)")),
	DCX_3200_HDGUIDE_SLNO_INPUT(XPATH,getPropValue("DCX3200HDGuide(518/517/516/511)SlNoInput")),
	
	RENT_DCX_3200_P2MTC(XPATH,getPropValue("DCX3200P2MTC(520/519)")),
	DCX_3200_P2MTC_SLNO_INPUT(XPATH,getPropValue("DCX3200P2MTC(520/519)SlNoInput")),
	
	RENT_DCX_DCX3400_500GB(XPATH,getPropValue("DCX3400(500GB)(505/500)")),
	DCX_DCX3400_500GB_SLNO_INPUT(XPATH,getPropValue("DCX3400(500GB)(505/500)SlNoInput")),
	                                                
	RENT_DCX_DCX3400_250GB(XPATH,getPropValue("DCX3400(250GB)(507/502)")),
	DCX_DCX3400_250GB_SLNO_INPUT(XPATH,getPropValue("DCX3400(250GB)(507/502)SlNoInput")),
	                                              
	RENT_DCX3510_HDGUIDE(XPATH,getPropValue("DCX3510HDGuide(522/521)")),
	DCX3510_HDGUIDE_SLNO_INPUT(XPATH,getPropValue("DCX3510HDGuide(522/521)SlNoInput")),
	
	RENT_SHAW_GATEWAY_HDPVR(XPATH,getPropValue("ShawGatewayHDPVR(525/524)")),
	SHAW_GATEWAY_HDPVR_SLNO_INPUT(XPATH,getPropValue("ShawGatewayHDPVR(525/524)SlNoInput")),
	
	RENT_SHAW_GATEWAY_PORTAL(XPATH,getPropValue("ShawGatewayPortal(415/410)")),
	SHAW_GATEWAY_PORTAL_SLNO_INPUT(XPATH,getPropValue("ShawGatewayPortal(415/410)SlNoInput")),
	
	RENT_SHAW_GATEWAY(XPATH,getPropValue("ShawGateway(515/510)")),
	SHAW_GATEWAY_SLNO_INPUT(XPATH,getPropValue("ShawGateway(515/510)SlNoInput")),
	
	RENT_SHAW_PORTAL(XPATH,getPropValue("ShawPortal(415/410)")),
	SHAW_PORTAL_SLNO_INPUT(XPATH,getPropValue("ShawPortal(415/410)SlNoInput")),
	
	RENT_SHAW_BLUESKY_TVBOX526(XPATH,getPropValue("ShawBlueSkyTVbox526")),
	SHAW_BLUESKY_TVBOX526_SLNO_INPUT(XPATH,getPropValue("ShawBlueSkyTVbox526_SlNoInput")),
	
	RENT_SHAW_BLUESKY_TVPORTAL416(XPATH,getPropValue("ShawBlueSkyTVportal416")),
	SHAW_BLUESKY_TVPORTAL416_SLNO_INPUT(XPATH,getPropValue("ShawBlueSkyTVportal416_SlNoInput")),
	
	RENT_SHAW_BLUESKY_TV_4KWIRELESS_BOX(XPATH,getPropValue("ShawBlueSkyTV4KWirelessBox")),
	SHAW_BLUESKY_TV_4KWIRELESS_BOX_INPUT(XPATH,getPropValue("ShawBlueSkyTV4KWirelessBoxSlNoInput")),
	
	RENT_SHAW_BLUESKY_TV4KBOX_530(XPATH,getPropValue("ShawBlueSkyTV4Kbox(530)")),
	SHAW_BLUESKY_TV4KBOX_530_SLNO_INPUT(XPATH,getPropValue("ShawBlueSkyTV4Kbox(530)Input")),
	
	MOXIGATEWAY_HDPVR525_BUY(XPATH,getPropValue("moxiGatewayHDPVR(525/524)Buy")),
	MOXIGATEWAY_HDPVR525_BUY_INPUT(XPATH,getPropValue("moxiGatewayHDPVR(525/524)BuyInput")),
	
	BLUECURVE_TV_PLAYER526_RENT_BTN(XPATH,getPropValue("BluecurveTVplayer526rentBtn")),
	BLUECURVE_TV_PLAYER526_INPUT(XPATH,getPropValue("BluecurveTVplayer526input")),
	
	BLUECURVE_TV_WIRELESS_4KPLAYER418_RENT(XPATH,getPropValue("blueCurveTVWireless4KPlayer418Rent")),
	BLUECURVE_TV_WIRELESS_4KPLAYER418_INPUT(XPATH,getPropValue("blueCurveTVWireless4KPlayer418")),
	
	
	CUSTOMER_OWNED_INPUT(XPATH,getPropValue("CustomerOwnedInput")),
	CUSTOMER_OWNED_DROPDOWN(XPATH,getPropValue("CustomerOwnedDropdown")),
	
	VALIDATE_SRL_NO(XPATH,getPropValue("validateHardware")),
	
	
	//********************Newly Added***************//
	
	SECONDARY_VOICEMAIL_CHECKBOX(XPATH,getPropValue("secondaryVoiceMailCheckBox")),
	EMAIL_IP_ADDRESS(XPATH,getPropValue("emailIPAddress")),
	DELETE_PHONE_LOB(XPATH,getPropValue("deletePhoneLOB")),
	SHAW_GATEWAY_RENTBTN(XPATH,getPropValue("shawGatewayRentBtn")),
	SHAW_PORTAL_RENTBTN(XPATH,getPropValue("shawPortalRentBtn")),
	PORTAL_PROMO24M_CHECKBTN(XPATH,getPropValue("portalPromoCheckBtn")),
	BUNDLES_PROMO_BTN(XPATH,getPropValue("bundlesPromoBtn")),
	TV_PROMO_24M(XPATH,getPropValue("tvPromo24M")),
	COUPON_SECTIONS(XPATH,getPropValue("couponsSections")),
	MAKE_GOOD_COUPON_CHECKBOX(XPATH,getPropValue("makeGoodCouponCheckBox")),
	COUPON_INCREASE_BTN(XPATH,getPropValue("couponIncreaseBtn")),
	CDI_STUB(XPATH,getPropValue("cdiStub")),
	LOCATIONID_TEXTBOX(XPATH,getPropValue("locationIdTextBox")),
	CREATE_BTN_STUB(XPATH,getPropValue("createBtnStub")),
	
	
	CBS_CUSTOMER_ACCOUNT_TYPE(XPATH,getPropValue("CBScustomerAccntType")),
	CBS_BULKMASTER_ACCOUNT(XPATH,getPropValue("CBSbulkmasterAccnt")),
	CBS_TENANT_ACCOUNT(XPATH,getPropValue("CBStenantAccnt")),
	CBS_RESIDENTAL_ACCOUNT(XPATH,getPropValue("CBSresidentalAccnt")),
	CBS_MASTER_ACCOUNT_INPUT(XPATH,getPropValue("CBSmasterAccntNoInput")),
	CBS_ACCOUNT_ID(XPATH,getPropValue("AccountId")),
	
	TYPE_2_RING_SHORT(XPATH,getPropValue("2ShortRingType")),
	LONG_DISTANCE_PRIVILEGES(XPATH,getPropValue("longDistancePrivileges")),
	LONG_DISTANCE_OPTION(XPATH,getPropValue("longDistanceOption")),
	IMMEDIATE_BILLING_PREFERENCES(XPATH,getPropValue("immediateBillingPreferences")),
	BILLING_CYCLE_DATE_INCBTN(XPATH,getPropValue("billingCycleDateIncBtn")),
	SET_PRFERRED_PAYMENT_DUE_DATE(XPATH,getPropValue("preferredPaymentBtn")),
	EXISTING_EMAIL_TWO(XPATH,getPropValue("existingEmailTwo")),
	RESET_PWD_CHECK_BOX(XPATH,getPropValue("resetPwdCheckBox")),
	DELETE_SECOND_EMAIL(XPATH,getPropValue("deleteSecondEmai")),
	ENGINEERING_NO_TV_BTN(XPATH,getPropValue("engineeringNoTVBtn")),
	MINIUM_PORTING_TIME(XPATH,getPropValue("minimumPortingTime")),
	INTEGRATION_SETTINGS_EDIT_BTN(XPATH,getPropValue("integrationSettingsEditBtn")),
	PROVISION_ON_CUST_ORDER_INPUT(XPATH,getPropValue("provisionOnCustOrderInput")),
	MINIUM_PORTING_TIME_INPUT(XPATH,getPropValue("minimumPortingTimeInput")),
	PORTING_TIME_UPDATE_BTN(XPATH,getPropValue("portingTimeUpdateBtn")),
    TRANSFER_CBS_CHECKBOX(XPATH,getPropValue("transferCBSCheckBox")),
    CBS_ACCOUNT_NBR(XPATH,getPropValue("cbsAccountNbr")),
    CBS_BRANCH_DROPDOWN(XPATH,getPropValue("cbsBranchDropdown")),
    CBS_ACCNT_VALIDATION_BTN(XPATH,getPropValue("cbsAccntValidationBtn")),
    DISTINCTIVERING_WRENCH1(XPATH,getPropValue("distinctiveRingWrench1")),
    DISTINCTIVERING_WRENCH2(XPATH,getPropValue("distinctiveRingWrench2")),
    APPLY_CHANGES_DISABLE(XPATH,getPropValue("applyChangesDisable")),
    PROVISION_ONCUST_CONFIRMATION(XPATH,getPropValue("provisionOnCusConfirmation")),
    ADVANCED_WIFI_MODEM_RENTAL_DISCOUNT(XPATH,getPropValue("advancedWiFiModemRentalDiscount")),
    CONFIRM_PROMOTION_BTN(XPATH,getPropValue("confirmPramotionBtn")),
    CONFIRM_PROMOTION_RESTART_BTN(XPATH,getPropValue("confirmPromotionRestartBtn")),
    OPERATIONS_DROPDOWN(XPATH,getPropValue("operationsDropdown")),
    RESET_CACHES(XPATH,getPropValue("resetCaches")),
    DB_CONFIRM_BTN(XPATH,getPropValue("dbconfirmBtn")),
    RETAIL_SELF_INSTALL_RADIO_BTN(XPATH,getPropValue("retailSelfInstallRadioBtn")),
    DIRECTFULFILLMENT_ORDER_DAYS(XPATH,getPropValue("directFulfillmentOrderDays")),
    DIRECTFULFILLMENT_ORDER_DAYS_INPUT(XPATH,getPropValue("directFulfillmentOrderDaysInput")),
    AUTO_CANCEL_FORDF_MONITORING(XPATH,getPropValue("autoCancelForDFMonitoring")),
	PROVISION_ON_CUST_ORDER_DAYS(XPATH,getPropValue("provisionOnCustOrderDays")),
	REASSIGN_LEVELUP_BTN1(XPATH,getPropValue("reAssignLevelUpBtn1")),
	REASSIGN_LEVELUP_BTN2(XPATH,getPropValue("reAssignLevelUpBtn2")),
	REASSIGN_LEVELUP_BTN3(XPATH,getPropValue("reAssignLevelUpBtn3")),
	REASSIGN_LEVELUP_BTN4(XPATH,getPropValue("reAssignLevelUpBtn4")),
	REASSIGN_LEVELUP_BTN5(XPATH,getPropValue("reAssignLevelUpBtn5")),
	HARDWARE_RECALL_CHECKBOX(XPATH,getPropValue("hardwareRecallCheckBox")),
	NEW_USER(XPATH,getPropValue("newUserLink")),
	USER_NAME_BOX(NAME,getPropValue("userNameBox")),
	OLD_PASSWORD(XPATH,getPropValue("oldPassword")),
	NEW_PASSWORD(NAME,getPropValue("newPassword")),
	CONFIRM_PASSWORD(NAME,getPropValue("confirmPassword")),
	USER_STATUS(XPATH,getPropValue("userStatus")),
	CREATE_BTN(XPATH,getPropValue("userCreateBtn")),
	NEED_TO_SCROLL_ELEMENT(XPATH,getPropValue("needToScrollElement")),
	ADDING_ROLES_DROPDOWN(XPATH,getPropValue("addingRolesDropdown")),
	//MAILOUT_PREMISEMOVE_OPTION_YES(XPATH,getPropValue("MailoutPremiseMoveOptionYes")),
	//MAILOUT_PREMISEMOVE_OPTION_NO(XPATH,getPropValue("MailoutPremiseMoveOptionNo")),
	ACTIVATE_OPTIONON_CONFIRMATION(XPATH,getPropValue("activateOptionOnConfirmation")),
	ACTIVATE_OPTION_ONDATE(XPATH,getPropValue("activateOptionOnADate")),
	TECHAPP_NO_VALIDATE_MSG(XPATH,getPropValue("techAppNoValidateMsg")),
	INT_AGR_REMOVE(XPATH,getPropValue("2YVPInternetAgreementRrmove")),
	PRISE_GUARENTEE_REMOVE(XPATH,getPropValue("24M2YVPInternet300PriceGuarRemove")),
	DEFAULT_INSTALLATION_MSG(XPATH,getPropValue("defaultInstallationMsg")),
	ACTIVATE_DIRECTORYID_REMOVEBTN(XPATH,getPropValue("activeDirectoryIdremoveBtn")),
	PREFERRED_DELIVERY_METHOD(XPATH,getPropValue("preferredDeliveryMethod")),
	AGREEMENT_DETAIL_TAB(XPATH,getPropValue("agreementDetailTab")),
	ACTIVATE_DIRECTORYID_INPUT(XPATH,getPropValue("activeDirectoryIdInput")),
	
	NEW_USER_TAB(XPATH,getPropValue("NewUser")),
	LOGIN_USER_NAME(XPATH,getPropValue("loginUserName")),
	USER_NAME_TAB(XPATH,getPropValue("userName")),
	

/******************** DISCONNECT REASONS **********************/
	
	REASON_CATEGORY_DROPDOWN(CLASS_NAME,getPropValue("reasonCatagoryDropdown")),
	CONTROLLABLE(XPATH,getPropValue("controllable")),
	NON_CONTROLLABLE(XPATH,getPropValue("nonControllable")),
	CAN_NO_LONGER_AFFORD(XPATH,getPropValue("canNoLongerAfford")),
	COMPITATIVE_PRAMOTIONS(XPATH,getPropValue("compitativePramotions")),
	CUSTOMERCARE_ISSUES(XPATH,getPropValue("customerCareIssues")),
	DOESNT_USE(XPATH,getPropValue("doesntUse")),
	PORT_OUT(XPATH,getPropValue("portOut")),
	PROMOTION_ENDED(XPATH,getPropValue("PromotionEnded")),
	TECHNICAL_ISSUES(XPATH,getPropValue("technicalIssues")),
	CUSTOMER_DECLINED_TOSAY(XPATH,getPropValue("customerDeclinedToSay")),
	DECEASED(XPATH,getPropValue("deceased")),
	LARGE_SCALE(XPATH,getPropValue("largeScale")),
	MOVE_ADDRESS(XPATH,getPropValue("moveAddress")),
	MOVE_OUTSIDE_SHAW(XPATH,getPropValue("moveOutSideShaw")),
	CUSTOMER_DECLINED_TO_SAY(XPATH,getPropValue("CustomerDeclinedToSay")),
    NON_PAY(XPATH,getPropValue("nonPay")),
	
	OPERATION(XPATH,getPropValue("Operation")),
	UNLOCK_ORDER(XPATH,getPropValue("unlockOrder")),
	YES_BTN(XPATH,getPropValue("YesBtn")),
	CLOSE_CBS(XPATH,getPropValue("closeCBS")),
	CONFIRM_ACTIVATION(XPATH,getPropValue("confirmActivation")),
	
	OE_ACCOUNT_NUMBER(XPATH,getPropValue("OEaccountNumber")),
	IS_IMMEDIATE_LOCKED(XPATH,getPropValue("IsImmediateLocked")),
	
	/******************** MUT **********************/
	NEW_MASS_ACCOUNT_UPDATE(XPATH,getPropValue("NewMassAccountUpdate")),
	UPDATE_QUOTE_EDIT_OPTN(XPATH,getPropValue("UpdateQuoteEditOptn")),
	UPDATE_QUOTE_EDIT_BTN(XPATH,getPropValue("UpdateQuoteEditBtn")),
	ADD_FILE_BTN(XPATH,getPropValue("AddFileBtn")),
	QUOTE_UPLOAD_BTN(XPATH,getPropValue("quoteUpdateBtn")),
	UPLOAD_BTN(XPATH,getPropValue("uploadBtn")),
	ACCOUNT_DATA_ADD_FILE_BTN(XPATH,getPropValue("AccountDataAddFileBtn")),
	RUN_BTN(XPATH,getPropValue("runBtn")),
	UPDATE_BTN(XPATH,getPropValue("updateBtn")),
	UPDATE_QUOTE_LINK(XPATH,getPropValue("UpdateQuoteLink")),
	EDIT_BTN(XPATH,getPropValue("EditBtn")),
	TOP_TAB(XPATH,getPropValue("topTab")),
	ACCOUNT_DATA(XPATH,getPropValue("AccountData")),
	MASS_UPDATE_TAB(XPATH,getPropValue("massUpdateTab")),
	PARALLEL_ORDER_INPUT(XPATH,getPropValue("parallelOrderInput")),
	PARALLEL_ORDER_DELAY_INPUT(XPATH,getPropValue("parallelOrderDelayInput")),
	BATCH_SIZE_INPUT(XPATH,getPropValue("BatchSizeInput")),
	ERRONEOUS_ORDER_INPUT(XPATH,getPropValue("ErroneousOrderInput")),
	SAVE_BTN(XPATH,getPropValue("SaveBtn")),
	STATUS_TEXT(XPATH,getPropValue("statusText")),
	DETAILED_REPORT_BTN(XPATH,getPropValue("DetailedReportBtn")),
	COMPLETED_TEXT(XPATH,getPropValue("completedText")),
	END_POINT_ADDRESS(XPATH,getPropValue("EndPointAddress")),
	END_POINT_UPDATE_BTN(XPATH,getPropValue("EndPointUpdateBtn")),
	COMX(XPATH,getPropValue("COMX")),
	CBS_ACCOUNT_NUMBER_INPUT(XPATH,getPropValue("cbsAccountNumberInput")),
	TELEPHONE_NUMBER_INPUT(XPATH,getPropValue("TelephoneNumberInput")),
	ADD_BTN(XPATH,getPropValue("AddBtn")),
	
	MIGRATE_RADIO_BTN(XPATH,getPropValue("migrateRadioBtn")),
	MIGRATE_PHN_NBR_INPUT(XPATH,getPropValue("migratePhnNbrInput")),
	MIGRATE_NOW_BTN(XPATH,getPropValue("migrateNowBtn")),
	FIRST_SELECT_NUMBER(XPATH,getPropValue("firstSelectNumber")),
	SECOND_SELECT_NUMBER(XPATH,getPropValue("secondSelectNumber")),
	FIRST_DISTICTIVE_RING_INPUT(XPATH,getPropValue("firstDistinctiveRingInput")),
	SECOND_DISTICTIVE_RING_INPUT(XPATH,getPropValue("secondDistinctiveRingInput")),
	FIRST_DR_SELECT_NUMBER(XPATH,getPropValue("firstDRselectNumber")),
	SECOND_DR_SELECT_NUMBER(XPATH,getPropValue("secondDistinctiveRingInput")),
//	FEATURES_TAB(XPATH,getPropValue("featuresTab"));
	DIRECTORY_LISTING_TAB(XPATH,getPropValue("DirectoryListingTab"));
	
	
	private Locator locator;
	private String expression;

	public static String getPropValue(String value){
        value = Utility.getValueFromPropertyFile( value, Constants.ORDER_CREATION_PAGE_PROP_PATH);
        return value;
    }
	
	OrderCreationPageElement(Locator locator, String expression){
		this.locator = locator;
		this.expression = expression;
	}
	
	public Locator getLocator() {
		return locator;
	}

	public String getValue() {
		return expression;
	}

	public By getBy(String...placeholder) {
		return ByType.getLocator(locator, expression, placeholder);
	}

}
